### ISSUE TITLE
os.getloadavg not working on Windows.

### ISSUE THREAD

**Issue by sigmantium** [amor71/LiuAlgoTrader#283] opened 2021-12-16 14:51 UTC
**Describe the bug**
Attempting to run the trader program once the market starts and the system try's to work out how many workers to spawn it crashes. My understanding is that os.getloadavg() doesn't work on windows.
The exact error message:
`Traceback (most recent call last):
  File "C:\Users\holy_\Projects\liualgotrader\.venv\Scripts\trader", line 220, in <module>
    num_consumer_processes = calc_num_consumer_processes()
  File "C:\Users\Projects\liualgotrader\.venv\Scripts\trader", line 126, in calc_num_consumer_processes
    load_avg = sum(os.getloadavg()) / 3
AttributeError: module 'os' has no attribute 'getloadavg'`

It could entirely be my poor setup, I've been struggling a bit to get things working

**To Reproduce**
1. On Windows Run "python ..\.venv\Scripts\trader"
2. Wait for market to open
3. Checks open positions then crashes.

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit

**Additional context**
The psutil package offers cross platform alternatives to the os system package. I have tested on Windows and confirm it is working but further tests would be needed to make sure it doesn't break anything on Linux or Mac. I will send through a PR for review.

**Comment by amor71** [comment] 2021-12-17 13:25
@sigmantium  thaks for pointing this out. The issue is that you're nissing the environment variable `NUM_CONSUMERS`. You need to set it to a number above 1.

**Comment by amor71** [comment] 2021-12-17 13:25
@sigmantium  thaks for pointing this out. The issue is that you're nissing the environment variable `NUM_CONSUMERS`. You need to set it to a number above 1.

**Comment by amor71** [comment] 2021-12-17 13:28
I suggest you take a look [here](https://liualgotrader.readthedocs.io/en/latest/Configuration.html) to make sure you're not missing additional configurations. I'l close this issue now, please re-open if you experience any issues.

**Closed by amor71** 2021-12-17 13:28 UTC
